### ISSUE TITLE
RFE: PM Fundamentals

### ISSUE THREAD

**Issue by ecamposl** [RedHatTraining/curriculum-onboarding#17]
**Welcome to Red Hat!**

Before you start with your project, there are a couple of things you should know.

### How do we manage our projects?

Here at Red Hat, projects are managed using a Scrum approach. 

Not every project uses Scrum, there is also Kanban, that may be useful depending on the project.

### What PM tool does the GLS team uses?

The GLS team is actually using ZenHub [^1], an app that overlaps with GitHub. [^2]

For you to get to know ZenHub, please refer to the following videos to get more knowledge about the tool.

[Zenhub Tutorial Videos](https://drive.google.com/drive/folders/1kJB9BCtBvHyMAxukm_D64BN1J8DjSmMI?usp=sharing)

[^1]: https://www.zenhub.com/
[^2]: https://github.com/

**Comment by dsacco15** [comment]
Picking this up to implement the changes to the PM Fundamentals section.

**Comment by dsacco15** [comment]
Changes implemented, PR created and assigned to Ed to review.

**Comment by dsacco15** [comment]
PR approved and branch merged to main.
