### ISSUE TITLE
RFE: Add list of chat rooms

### ISSUE THREAD

**Issue by sffrench** [RedHatTraining/curriculum-onboarding#19]
Personas - Technical Editor - Chat Rooms: 

- The Editors Guild
- Content Services
- Word Nerds
- GLS Asciidoc
- Writers Curriculum Corner
- Curriculum_Core
- Curriculum Dev

@RedHatTraining/content-services Is there anything I am missing. This would be under the Technical Editor persona.

**Comment by dsacco15** [comment]
@daobrien Here is another that is in your domain as well.

**Comment by daobrien** [comment]
I expect this list belongs under the Admin tab that Dave's been working on, which includes mandatory email lists, etc.
The only one I see missing is #GLS-Tools and maybe #GLS-AsciiDoc

**Comment by sffrench** [comment]
Yes, was wondering where the best place to put it would be, it will be for the most part a repetitive list if placed under each persona.   However, I do see value in putting very role-specific rooms in their own section. It would take away the guessing game "Does this apply to me specifically?"
