### ISSUE TITLE
RFE: Add XML and Tech Review Process

### ISSUE THREAD

**Issue by sffrench** [RedHatTraining/curriculum-onboarding#20]
Personas - Technical Editor - XML and Tech Review Process -  https://source.redhat.com/groups/public/gls-content-services/gls_content_services_wiki/rht_xml_and_tech_review_process

Suggest adding this link or some of the content: XML and Tech Review Process.
Maybe the XML stuff is not needed? But the Tech review process would be beneficial. 

@RedHatTraining/content-services

**Comment by dsacco15** [comment]
@daobrien could you pick this one up since it's in a section I am not all that familiar with?

**Comment by daobrien** [comment]
Yeah I have a few things to add related to this. Not sure if the detailed stuff will fit in the "first 30 days" frame but will investigate.
